### ISSUE TITLE
goreleaser

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/go-whosonfirst-format#6]
I've seen this cool package [goreleaser](https://github.com/goreleaser/goreleaser), but not had a chance to use it yet.

It looks like we can configure it to do a bunch of pre-release tasks, but the one I'd love to see is to build and attach precompiled binary 'assets' to the 'releases' on Github.

See one of their releases as example:
https://github.com/goreleaser/goreleaser/releases/tag/v0.175.0

<img width="672" alt="Screenshot 2021-08-23 at 15 00 50" src="https://user-images.githubusercontent.com/738069/130451535-329f3ea8-ba98-4fa4-b831-877f5aa5a32c.png">

**Comment by thisisaaronland** [comment]
There are a bunch of places something like this would be useful. Does it require Docker to publish releases? Is it something that we could automate using plain-vanilla Go commands and GitHub actions?

**Comment by missinglink** [comment]
Looks like github actions can handle it all for us https://goreleaser.com/ci/actions/

**Comment by tomtaylor** [comment]
I’m happy to try and wire this up. It’d be useful to automatically release binaries for a bunch of different architectures and be able to install them with `brew` for those of us on MacOS. The same goes for all the WOF executables, so maybe there’s a common approach we can apply across other packages.

**Comment by thisisaaronland** [comment]
Agreed. This would be very useful for the tools in `go-whosonfirst-exportify`.

**Comment by tomtaylor** [comment]
Released and working in #9.
